#ifndef __MSC_NR_IMX6_COMMON_H__
#define __MSC_NR_IMX6_COMMON_H__
/*
 * Copyright (C) 2015 MSC Technologies
 *       <www.msc-technologies.eu>
 *
 * SPDX-License-Identifier:	GPL-2.0
 */

#define UART_PAD_CTRL \
	(PAD_CTL_HYS | PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED | \
			PAD_CTL_DSE_40ohm | PAD_CTL_SRE_FAST)

#define USDHC_PAD_CTRL \
	(PAD_CTL_HYS | PAD_CTL_PUS_47K_UP | PAD_CTL_SPEED_LOW | \
		PAD_CTL_DSE_80ohm | PAD_CTL_SRE_FAST)

#define ENET_PAD_CTRL \
	(PAD_CTL_HYS | PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED | \
			PAD_CTL_DSE_40ohm)

#define ENET_PAD_CTRL_NO_PULL \
	(PAD_CTL_HYS | PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm | \
		PAD_CTL_SRE_SLOW)

#define I2C_PAD_CTRL \
	(PAD_CTL_HYS | PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED | \
			PAD_CTL_DSE_40ohm | PAD_CTL_ODE | PAD_CTL_SRE_FAST)

#define SPI_PAD_CTRL \
	(PAD_CTL_HYS | PAD_CTL_PUS_100K_DOWN | PAD_CTL_SPEED_MED | \
			PAD_CTL_DSE_40ohm | PAD_CTL_SRE_FAST)

#define USB_OTG_PAD_CTRL \
	(PAD_CTL_HYS | PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED | \
			PAD_CTL_DSE_40ohm | PAD_CTL_SRE_SLOW)

#define GPIO_PAD_CTRL \
	(PAD_CTL_PUS_100K_DOWN | PAD_CTL_PUE | PAD_CTL_PKE | \
			PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm | \
			PAD_CTL_SRE_FAST)

#define RGB_PAD_CTRL \
	(PAD_CTL_DSE_120ohm)

#define WEAK_PULLUP \
	(PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm | \
			PAD_CTL_HYS | PAD_CTL_SRE_SLOW)

#define I2C2_MUX_GPIO	IMX_GPIO_NR(1, 7)

#endif /* __MSC_NR_IMX6_COMMON_H__ */
